# Site settings
title: Dean Record
description: Software Engineer
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://deanrecord.dev" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dean Record
user_description: I'm a Software Engineer, always searching for the next challenge. Currently @<a href="https://www.db.com">Deutsche Bank</a> in London, working in the trade finance risk domain.
user_title: Software Engineer
email: dean@deanrecord.dev
github_username:  deanrecord
linkedin_username: dean_record

exclude: ['package.json', 'src' , 'node_modules']
include: [".well-known"]
